# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vorortapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Custom_Widgets.Widgets import *
import numpy as np
import matplotlib.pyplot as plt
import speech_recognition as sr
import hl7
import socket
from hl7 import *





class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 600)
        MainWindow.setStyleSheet("#upline{\n"
"background-color: #ffaa00;\n"
"}\n"
"#frame{\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"#mainframe{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#fallanlegen,#datainputs,#diagnos,#messung,#datatransport,#anlegen,#qrcode,#eingabe,#messungstaste,#micro,#uploade{\n"
"border-radius: 20px; \n"
"background-color: #ffffff;\n"
" padding: 10px 20px;\n"
"  color: #aaffff; \n"
"  border: none; \n"
"border: 2px solid #000000;\n"
"}\n"
"#fallanlegen:hover,#datainputs:hover,#diagnos:hover,#messung:hover,#datatransport:hover,#anlegen:hover,#qrcode:hover,#eingabe:hover,#messungstaste:hover,#micro:hover,#uploade:hover{\n"
"background-color:#aaffff;\n"
"}\n"
"#input1,#input2,#input3,#spinBox,#pdvorname,#pd_name,#pd_geb,#pd_krank,#pd_ange{\n"
"background-color:#ffffff;\n"
"border: 2px solid #cccccc;\n"
"border-radius: 8px;\n"
" padding: 10px 20px;\n"
"}\n"
"#input1:hover,#input2:hover,#input3:hover,#spinBox:hover{\n"
"background-color:#aaffff;\n"
"}\n"
"")     
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.upline = QtWidgets.QFrame(self.centralwidget)
        self.upline.setGeometry(QtCore.QRect(0, 0, 821, 91))
        self.upline.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upline.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upline.setObjectName("upline")
        self.fallanlegen = QtWidgets.QPushButton(self.upline)
        self.fallanlegen.setGeometry(QtCore.QRect(50, 10, 111, 71))
        self.fallanlegen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/005-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fallanlegen.setIcon(icon)
        self.fallanlegen.setIconSize(QtCore.QSize(70, 70))
        self.fallanlegen.setObjectName("fallanlegen")
        self.datainputs = QtWidgets.QPushButton(self.upline)
        self.datainputs.setGeometry(QtCore.QRect(220, 10, 81, 71))
        self.datainputs.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/002-medical-notes-symbol-of-a-list-paper-on-a-clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datainputs.setIcon(icon1)
        self.datainputs.setIconSize(QtCore.QSize(75, 75))
        self.datainputs.setObjectName("datainputs")
        self.messung = QtWidgets.QPushButton(self.upline)
        self.messung.setGeometry(QtCore.QRect(380, 10, 91, 71))
        self.messung.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/001-tray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messung.setIcon(icon2)
        self.messung.setIconSize(QtCore.QSize(75, 75))
        self.messung.setObjectName("messung")
        self.messung.clicked.connect(self.loadwerte)
        self.diagnos = QtWidgets.QPushButton(self.upline)
        self.diagnos.setGeometry(QtCore.QRect(530, 10, 81, 71))
        self.diagnos.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/009-doctor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.diagnos.setIcon(icon3)
        self.diagnos.setIconSize(QtCore.QSize(75, 75))
        self.diagnos.setObjectName("diagnos")
        self.datatransport = QtWidgets.QPushButton(self.upline)
        self.datatransport.setGeometry(QtCore.QRect(680, 10, 91, 71))
        self.datatransport.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/003-upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datatransport.setIcon(icon4)
        self.datatransport.setIconSize(QtCore.QSize(65, 65))
        self.datatransport.setObjectName("datatransport")
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        self.mainframe.setGeometry(QtCore.QRect(0, 90, 811, 501))
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.stackedWidget = QCustomStackedWidget(self.mainframe)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 811, 501))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.label = QtWidgets.QLabel(self.page1)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 51))
        self.label.setObjectName("label")
        self.anlegen = QtWidgets.QPushButton(self.page1)
        self.anlegen.setGeometry(QtCore.QRect(50, 80, 131, 111))
        self.anlegen.setText("")
        self.anlegen.clicked.connect(self.anlegfunk)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/007-group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.anlegen.setIcon(icon5)
        self.anlegen.setIconSize(QtCore.QSize(75, 75))
        self.anlegen.setObjectName("anlegen")
        self.input3 = QtWidgets.QLineEdit(self.page1)
        self.input3.setGeometry(QtCore.QRect(290, 200, 181, 71))
        self.input3.setObjectName("input3")
        self.input3.setVisible(False)
        self.input1 = QtWidgets.QLineEdit(self.page1)
        self.input1.setGeometry(QtCore.QRect(290, 100, 171, 41))
        self.input1.setObjectName("input1")
        self.input1.setVisible(False)
        self.spinBox = QtWidgets.QSpinBox(self.page1)
        self.spinBox.setGeometry(QtCore.QRect(290, 150, 171, 41))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setVisible(False)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.label_2 = QtWidgets.QLabel(self.page2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 271, 51))
        self.label_2.setObjectName("label_2")
        self.qrcode = QtWidgets.QPushButton(self.page2)
        self.qrcode.setGeometry(QtCore.QRect(60, 80, 101, 91))
        self.qrcode.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/camera_disabled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qrcode.setIcon(icon6)
        self.qrcode.setIconSize(QtCore.QSize(70, 70))
        self.qrcode.setObjectName("qrcode")
        self.eingabe = QtWidgets.QPushButton(self.page2)
        self.eingabe.setGeometry(QtCore.QRect(270, 80, 111, 81))
        self.eingabe.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/edit-3_disabled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eingabe.setIcon(icon7)
        self.eingabe.setIconSize(QtCore.QSize(70, 70))
        self.eingabe.setObjectName("eingabe")
        #function einer Button einfügen
        self.eingabe.clicked.connect(self.erfassfunk)
        self.pdvorname = QtWidgets.QLineEdit(self.page2)
        self.pdvorname.setGeometry(QtCore.QRect(70, 200, 141, 41))
        self.pdvorname.setObjectName("pdvorname")
        self.pdvorname.setVisible(False)
        self.pd_name = QtWidgets.QLineEdit(self.page2)
        self.pd_name.setGeometry(QtCore.QRect(70, 250, 141, 41))
        self.pd_name.setObjectName("pd_name")
        self.pd_name.setVisible(False)
        self.pd_geb = QtWidgets.QLineEdit(self.page2)
        self.pd_geb.setGeometry(QtCore.QRect(70, 300, 141, 41))
        self.pd_geb.setObjectName("pd_geb")
        self.pd_geb.setVisible(False)
        self.pd_krank = QtWidgets.QLineEdit(self.page2)
        self.pd_krank.setGeometry(QtCore.QRect(240, 200, 131, 41))
        self.pd_krank.setObjectName("pd_krank")
        self.pd_krank.setVisible(False)
        self.pd_ange = QtWidgets.QLineEdit(self.page2)
        self.pd_ange.setGeometry(QtCore.QRect(240, 250, 141, 41))
        self.pd_ange.setObjectName("pd_ange")
        self.pd_ange.setVisible(False)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.label_3 = QtWidgets.QLabel(self.page3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.label_3.setObjectName("label_3")
        self.messungstaste = QtWidgets.QPushButton(self.page3)
        self.messungstaste.setGeometry(QtCore.QRect(60, 80, 181, 111))
        self.messungstaste.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons/001-cardiogram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messungstaste.setIcon(icon8)
        self.messungstaste.setIconSize(QtCore.QSize(100, 100))
        self.messungstaste.setObjectName("messungstaste")
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.label_4 = QtWidgets.QLabel(self.page4)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 311, 51))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page4)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 170, 591, 271))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.micro = QtWidgets.QPushButton(self.page4)
        self.micro.setGeometry(QtCore.QRect(70, 50, 181, 101))
        self.micro.setText("")
        self.micro.clicked.connect(self.memoTalk)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons/mic_focus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.micro.setIcon(icon9)
        self.micro.setIconSize(QtCore.QSize(80, 80))
        self.micro.setObjectName("micro")
        self.stackedWidget.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.label_5 = QtWidgets.QLabel(self.page5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 581, 81))
        self.label_5.setObjectName("label_5")
        self.uploade = QtWidgets.QPushButton(self.page5)
        self.uploade.setGeometry(QtCore.QRect(120, 130, 191, 91))
        self.uploade.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons/008-upload-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploade.setIcon(icon10)
        self.uploade.setIconSize(QtCore.QSize(80, 80))
        self.uploade.setObjectName("uploade")
        self.uploade.clicked.connect(self.conec)
        self.stackedWidget.addWidget(self.page5)
        MainWindow.setCentralWidget(self.centralwidget)
        

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        loadJsonStyle(self,ui)

    def retranslateUi(self, MainWindow):
      _translate = QtCore.QCoreApplication.translate
      self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#8b8b8b;\">Notfall anlegen:</span></p></body></html>"))
      self.input3.setPlaceholderText(_translate("MainWindow", "Beschreibung"))
      self.input1.setPlaceholderText(_translate("MainWindow", "Ort"))
      self.spinBox.setSpecialValueText(_translate("MainWindow", "Anzahl"))
      self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#969696;\">Patientendaten erfassen:</span></p></body></html>"))
      self.pdvorname.setPlaceholderText(_translate("MainWindow", "Vorname"))
      self.pd_name.setPlaceholderText(_translate("MainWindow", "Name"))
      self.pd_geb.setPlaceholderText(_translate("MainWindow", "Geb.datum"))
      self.pd_krank.setPlaceholderText(_translate("MainWindow", "Telefon"))
      self.pd_ange.setPlaceholderText(_translate("MainWindow", "Angehörige"))
      self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#9c9c9c;\">Messungen:</span></p></body></html>"))
      self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#7a7a7a;\">Einschätzung des Notarztes:</span></p></body></html>"))
      self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#7e7e7e;\">Daten mit HL7 an das zuständige Krankenhaus übertragen:</span></p></body></html>"))
    def anlegfunk(self):
        #funktionen wieder on 
        self.input1.setVisible(True)
        self.spinBox.setVisible(True)
        self.input3.setVisible(True)

        #eingaben einlesen in variabeln 
        ort= self.input1.text()
        anzahl = self.spinBox.text()
        desc= self.input3.text()

    # funktio, um Patientendaten zu erfassen 
    def erfassfunk(self):
        
        self.pdvorname.setVisible(True)
        self.pd_name.setVisible(True)
        self.pd_geb.setVisible(True)
        self.pd_krank.setVisible(True)
        self.pd_ange.setVisible(True)

        vorname = self.pdvorname.text()
        nname= self.pd_name.text()
        geb = self.pd_geb.text()
        tel=self.pd_krank.text()
        ange= self.pd_ange.text()

        return vorname,nname,geb,tel,ange

    #Beispiel, über dateneingabe und Anzeige   
    def loadwerte(self):
        # pfad zu der data 
        npy_data = 'ecg_ppg_data.npy'
        #data laden
        data= np.load(npy_data)
        plt.plot(data)
        plt.show()
        return plt.plot(data)

     #function, um Einschätzung verbal aufzunehmen
    def memoTalk(self):
        # Recognizer-Objekt
        rec = sr.Recognizer()

        # Mikrofon-Objekt
        micro = sr.Microphone()

        # Spracherkennung
        language = "de-DE"
        with micro as source:
            audio = rec.listen(source)
        
        try:
            # Spracheingabe erkennen
            text = rec.recognize_google(audio, language=language)
            self.plainTextEdit.setPlainText(text)
        except sr.UnknownValueError:
            print("Spracheingabe nicht erkannt")
        except sr.RequestError as e:
            print("Fehler bei der Spracherkennung: {0}".format(e))
        return self.plainTextEdit.setPlainText(text)
    def conec (self):
        


        pass 



    
        
        


       

        

from Custom_Widgets.Widgets import QCustomSlideMenu, QCustomStackedWidget
import resources_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
